### ISSUE TITLE
nn_id=retrain_sherlock does not generate loss value

### ISSUE THREAD

**Issue by devisrivarshny** [mitmedialab/sherlock-project#11]
Hi, I am trying to use Sherlock model for schematic field type prediction. I tried for large and small amount of data but whenever i try to train the model with nn_id=retrain_sherlock out of 100epochs it is running only for 5epochs and stops, the loss value is NaN from 1st epoch. The predictions for all the fieldtype is email. And i tried different things to solve the issue like checking the null values etc but nothing did not work still facing the same error. Please let me know if i am missing something and help me to resolve this issue. Thanks

**Comment by drimyus** [comment]
Hi @devisrivarshny , 
Please check your train data (preprocessed), there might be np.nan value.

**Comment by sylmorin-gbif** [comment]
Hi @devisrivarshny 
I agree with @drimyus , I had the same issue and it was related to null values after the extract_features()
Please use fillna on the dataframe.

```
X_train = extract_features(xtemp_train)
X_train.fillna(value=0, inplace=True)
```

**Comment by madelonhulsebos** [comment]
Thanks for your assistance on this issue @sylmorin-gbif and @drimyus. I hope it worked out. If it did not, the current release fixes some bugs on the feature extraction code thanks to @lowecg. This may solve your problem as well.
