### ISSUE TITLE
Varsha

### ISSUE THREAD

**Issue by varsha222** [mitmedialab/sherlock-project#15]
Why using raw data with pretrained model accuracy is only 56% while preprocessed data with pretrained model accuracy is 89%?

**Comment by madelonhulsebos** [comment]
Hi @varsha222, a discrepancy was introduced after a code rewrite. I am not sure what the cause is but will check soon.

**Comment by hiten26** [comment]
Hi @varsha222,

Given that feature extraction can take long, they have only taken the first 100 samples.

If you can use a high configure machine then you can try with complete test data.

**Comment by buddhareddy** [comment]
hi @hiten26  i need your help to use this model in google colab for my project purpose kindly help me.

here is my emai: buddhareddy.polepelli@gmail.com i require your 30 mins time for setup its a request from myend

**Comment by madelonhulsebos** [comment]
Hi @varsha222, please rerun your training process with the new release. It provides faster feature extraction procedures contributed by @lowecg, which makes it easier to retrain Sherlock on the full data. Please report a new issue if you have additional questions.
