### ISSUE TITLE
Any scope for re-training with new classes outside pre-trained 78 classes?

### ISSUE THREAD

**Issue by hiten26** [mitmedialab/sherlock-project#17]
Thank you so much for this wonderful work.

Do you guys have any plan for re-training the model with new classes apart from 78 classes? 

Do you guys have any plan for providing an option for changing the word-embedding technique?

**Comment by madelonhulsebos** [comment]
Hi @hiten26,

Thanks for your interest in our work!
We are currently working on a new dataset for training type detection models with more classes and more data.
I hope to provide also a more modular implementation of Sherlock (or a similar model) to facilitate different use-cases and configurations at some point.

Stay tuned!

**Comment by vipul25-ds** [comment]
Hello,

This is really an amazing work. I am trying to use this for some domain specific use cases.

@madelonhulsebos May I know if you have any update on  this thread.

**Comment by madelonhulsebos** [comment]
Hi all,

The current release includes the model code, see sherlock/deploy/model.py. This enables retraining with any class you like and adjusting the network architecture. The number of classes is automatically inferred from the training labels (unique labels). Please let me know if you have any questions or run into issues!

Best,
Madelon
