### ISSUE TITLE
Gensim Doc2Vec Error when loading para_vec_trained_400.pkl

### ISSUE THREAD

**Issue by lakithasahan** [mitmedialab/sherlock-project#18]
Getting a numpy error when loading the model.

ValueError: cannot reshape array of size 28232988 into shape (412059,400)

Any suggestions to fix this issue?

**Comment by lakithasahan** [comment]
Complete para_vec model havent downloaded properly, re-download fixed th issue.

**Comment by madelonhulsebos** [comment]
Thanks for sharing @lakithasahan!
