### ISSUE TITLE
How to train Sherlock?

### ISSUE THREAD

**Issue by bhart12** [mitmedialab/sherlock-project#19]
I see that the jupyter notebook, "demo_usage_sherlock.ipynb" is included to be able to see how to retrain the model. However, in the jupyter notebook, when "train_sherlock(X_train, y_train, X_val, y_val, nn_id='retrained_sherlock');" is called, none of the parameters that are being passed in have been declared before this, therefore the function obviously fails. I've tried several ways to create these missing variables for X_train, y_train, X_val, and y_val, but keep getting errors. I was wondering how you create these X_train, y_train, X_val, and y_val to pass into the train_sherlock() function.

**Comment by madelonhulsebos** [comment]
Hi @bhart12,

I am not familiar with this issue, it should work. Could you share the error(s) that you're running into?

Thanks!

**Comment by bhart12** [comment]
So in the current notebook you have (notebooks/demo_usage_sherlock.ipynb), under the "Retrain Sherlock" label you have the following line:
![image](https://user-images.githubusercontent.com/37195929/110030116-50dd8200-7d03-11eb-8acc-85473efce259.png)

However, nowhere before this line are the variables X_train, y_train, X_val, or y_val declared in the notebook. So I tried to create these variables in the same way that the X_test variables were created. I have copied and pasted the lines of code I'm doing this with below:

###CODE STARTS HERE###
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score
import tensorflow as tf

from sherlock import helpers
from sherlock.features.preprocessing import extract_features, convert_string_lists_to_lists, prepare_feature_extraction
from sherlock.deploy.train_sherlock import train_sherlock
from sherlock.deploy.predict_sherlock import predict_sherlock

train_samples = pd.read_parquet('../data/data/raw/train_values.parquet')
train_labels = pd.read_parquet('../data/data/raw/train_labels.parquet')
validation_samples = pd.read_parquet('../data/data/raw/val_values.parquet')
validation_labels = pd.read_parquet('../data/data/raw/val_labels.parquet')

train_samples_converted, y_train = convert_string_lists_to_lists(train_samples, train_labels, "values", "type")
validate_samples_converted, y_validate = convert_string_lists_to_lists(validation_samples, validation_labels, "values", "type")

X_train = extract_features(train_samples_converted.head(n=100))
X_validation = extract_features(validate_samples_converted.head(n=100))

train_sherlock(X_train, y_train_subset, X_validation, y_validate_subset, nn_id='retrained_sherlock');

###CODE ENDS HERE###

However, when I get to the train_sherlock() function, I get the following error message:

###START OF ERROR MESSAGE###
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-3025f27c243c> in <module>
---> 19 train_sherlock(X_train, y_train_subset, X_validation, y_validate_subset, nn_id='retrained_sherlock');

~/Documents/School/COP5725/Sherlock/mitVersion/sherlock-project-master/notebooks/sherlock/deploy/train_sherlock.py in train_sherlock(X_train, y_train, X_val, y_val, nn_id)
    103 
    104 
--> 105     sherlock_model.fit(
    106         [
    107             X_train[feature_cols['char']].values,

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1048          training_utils.RespectCompiledTrainableState(self):
   1049       # Creates a `tf.data.Dataset` and handles batch and epoch iteration.
-> 1050       data_handler = data_adapter.DataHandler(
   1051           x=x,
   1052           y=y,

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution)
   1098 
   1099     adapter_cls = select_data_adapter(x, y)
-> 1100     self._adapter = adapter_cls(
   1101         x,
   1102         y,

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, sample_weight_modes, batch_size, epochs, steps, shuffle, **kwargs)
    261                **kwargs):
    262     super(TensorLikeDataAdapter, self).__init__(x, y, **kwargs)
--> 263     x, y, sample_weights = _process_tensorlike((x, y, sample_weights))
    264     sample_weight_modes = broadcast_sample_weight_modes(
    265         sample_weights, sample_weight_modes)

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py in _process_tensorlike(inputs)
   1014     return x
   1015 
-> 1016   inputs = nest.map_structure(_convert_numpy_and_scipy, inputs)
   1017   return nest.list_to_tuple(inputs)
   1018 

~/.local/lib/python3.8/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    657 
    658   return pack_sequence_as(
--> 659       structure[0], [func(*x) for x in entries],
    660       expand_composites=expand_composites)
    661 

~/.local/lib/python3.8/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    657 
    658   return pack_sequence_as(
--> 659       structure[0], [func(*x) for x in entries],
    660       expand_composites=expand_composites)
    661 

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py in _convert_numpy_and_scipy(x)
   1009       if issubclass(x.dtype.type, np.floating):
   1010         dtype = backend.floatx()
-> 1011       return ops.convert_to_tensor_v2_with_dispatch(x, dtype=dtype)
   1012     elif scipy_sparse and scipy_sparse.issparse(x):
   1013       return _scipy_sparse_to_sparse_tensor(x)

~/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor_v2_with_dispatch(value, dtype, dtype_hint, name)
   1402     ValueError: If the `value` is a tensor not of given `dtype` in graph mode.
   1403   """
-> 1404   return convert_to_tensor_v2(
   1405       value, dtype=dtype, dtype_hint=dtype_hint, name=name)
   1406 

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
   1408 def convert_to_tensor_v2(value, dtype=None, dtype_hint=None, name=None):
   1409   """Converts the given `value` to a `Tensor`."""
-> 1410   return convert_to_tensor(
   1411       value=value,
   1412       dtype=dtype,

~/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py in wrapped(*args, **kwargs)
    161         with Trace(trace_name, **trace_kwargs):
    162           return func(*args, **kwargs)
--> 163       return func(*args, **kwargs)
    164 
    165     return wrapped

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
   1538 
   1539     if ret is None:
-> 1540       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1541 
   1542     if ret is NotImplemented:

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_conversion_registry.py in _default_conversion_function(***failed resolving arguments***)
     50 def _default_conversion_function(value, dtype, name, as_ref):
     51   del as_ref  # Unused.
---> 52   return constant_op.constant(value, dtype, name=name)
     53 
     54 

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name)
    262     ValueError: if called on a symbolic tensor.
    263   """
--> 264   return _constant_impl(value, dtype, shape, name, verify_shape=False,
    265                         allow_broadcast=True)
    266 

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    274       with trace.Trace("tf.constant"):
    275         return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
--> 276     return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
    277 
    278   g = ops.get_default_graph()

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py in _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
    299 def _constant_eager_impl(ctx, value, dtype, shape, verify_shape):
    300   """Implementation of eager constant."""
--> 301   t = convert_to_eager_tensor(value, ctx, dtype)
    302   if shape is None:
    303     return t

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     96       dtype = dtypes.as_dtype(dtype).as_datatype_enum
     97   ctx.ensure_initialized()
---> 98   return ops.EagerTensor(value, ctx.device_name, dtype)
     99 
    100 

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type bool).

###END OF ERROR MESSAGE###

**Comment by uucico** [comment]
If you notice the X_train data has booleans in fields such as `n_[0]-agg-any `and `n_[0]-agg-all`. I replaced the following section of `sherlock_model.predict `to convert them from categorial.

```
    y_pred = sherlock_model.predict(
        [
            np.asarray(X[feature_cols_dict['char']].values).astype(np.float32),
            np.asarray(X[feature_cols_dict['word']].values).astype(np.float32),
            np.asarray(X[feature_cols_dict['par']].values).astype(np.float32),
            np.asarray(X[feature_cols_dict['rest']].values).astype(np.float32)
        ]
    )
```

It reproduces the example notebook results, but not sure if it's a sound approach. Ideas welcome and I hope this helps.

**Comment by bhart12** [comment]
@uucico @madelonhulsebos 
So I tried the change you made above. Please note that I am trying to fix the train_sherlock function, not the predict_sherlock function. However, I followed your approach and changed this section of the train_sherlock function:
'''
sherlock_model.fit(
        [
            X_train[feature_cols['char']].values,
            X_train[feature_cols['word']].values,
            X_train[feature_cols['par']].values,
            X_train[feature_cols['rest']].values,
        ],
        y_train_cat,
        validation_data=(
            [
                X_val[feature_cols['char']].values,
                X_val[feature_cols['word']].values,
                X_val[feature_cols['par']].values,
                X_val[feature_cols['rest']].values,
            ],
            y_val_cat
        ),
        callbacks=callbacks, epochs=100, batch_size=256
    )
'''
To this:
'''
sherlock_model.fit(
        [
            np.asarray(X_train[feature_cols['char']].values).astype(np.float32),
            np.asarray(X_train[feature_cols['word']].values).astype(np.float32),
            np.asarray(X_train[feature_cols['par']].values).astype(np.float32),
            np.asarray(X_train[feature_cols['rest']].values).astype(np.float32)
        ],
        y_train_cat,
        validation_data=(
            [
                np.asarray(X_train[feature_cols['char']].values).astype(np.float32),
                np.asarray(X_train[feature_cols['word']].values).astype(np.float32),
                np.asarray(X_train[feature_cols['par']].values).astype(np.float32),
                np.asarray(X_train[feature_cols['rest']].values).astype(np.float32)
            ],
            y_val_cat
        ),
        callbacks=callbacks, epochs=100, batch_size=256
    )
'''

However now I am getting the following error:
'''
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-3025f27c243c> in <module>
---> 19 train_sherlock(X_train, y_train_subset, X_validation, y_validate_subset, nn_id='retrained_sherlock');

~/.local/lib/python3.8/site-packages/sherlock/deploy/train_sherlock.py in train_sherlock(X_train, y_train, X_val, y_val, nn_id)
    104 
--> 105     sherlock_model.fit(
    106         [
    107             np.asarray(X_train[feature_cols['char']].values).astype(np.float32),

~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    869       # This is the first call of __call__, so we have to initialize.
    870       initializers = []
--> 871       self._initialize(args, kwds, add_initializers_to=initializers)
    872     finally:
    873       # At this point we know that the initialization is complete (or less

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    723     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    724     self._concrete_stateful_fn = (
--> 725         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    726             *args, **kwds))
    727 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2967       args, kwargs = None, None
   2968     with self._lock:
-> 2969       graph_function, _ = self._maybe_define_function(args, kwargs)
   2970     return graph_function
   2971 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3359 
   3360           self._function_cache.missed.add(call_context_key)
-> 3361           graph_function = self._create_graph_function(args, kwargs)
   3362           self._function_cache.primary[cache_key] = graph_function
   3363 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3194     arg_names = base_arg_names + missing_arg_names
   3195     graph_function = ConcreteFunction(
-> 3196         func_graph_module.func_graph_from_py_func(
   3197             self._name,
   3198             self._python_function,

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    988         _, original_func = tf_decorator.unwrap(python_func)
    989 
--> 990       func_outputs = python_func(*func_args, **func_kwargs)
    991 
    992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    632             xla_context.Exit()
    633         else:
--> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    635         return out
    636 

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:755 train_step
        loss = self.compiled_loss(
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:203 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:152 __call__
        losses = call_fn(y_true, y_pred)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:256 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:1537 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4833 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /home/bryce/.local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1134 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 78) are incompatible
'''

**Comment by bhart12** [comment]
So I might have figured out my issue. I made the changes to both the train_sherlock function and predict_sherlock function that are shown above. I think my program was not working because I have been trying to train the model on only part of the data (to save time), but it seems that the train_sherlock function will not work if all 78 different training labels are not in the y_train and y_val variables. For example, I was only taking the first 100 values of the training labels, as shown below

```
y_train_subset = y_train[:100]
y_validate_subset = y_validate[:100]
X_train = extract_features(train_samples_converted.head(n=100))
X_validation = extract_features(validate_samples_converted.head(n=100))

```
However, the first 100 entries in y_train and y_validate do not contain all 78 unique values that are in these lists. I found that all 78 unique values are not introduced in the lists until about the first 2900 elements. Therefore, I have changed my code to the following, which does not hit any errors when the train_sherlock function is called:
```
y_train_subset = y_train[:2900]
y_validate_subset = y_validate[:2900]
X_train = extract_features(train_samples_converted.head(n=2900))
X_validation = extract_features(validate_samples_converted.head(n=2900))
train_sherlock(X_train, y_train_subset, X_validation, y_train_subset, nn_id='retrained_sherlock');
```

This does work, though I am still curious if the added changes to the train_sherlock and predict_sherlock functions are valid corrections that will still yield similar results to what the original authors got when training and predicting the data. Again this was just adding the following to the values being passed when predicting and fitting the model (original changes shown above in previous comments):
```
np.asarray(...).astype(np.float32)
```

**Comment by sylmorin-gbif** [comment]
@bhart12 
If you are training your model with less than the 78 labels (and if you know how many labels you have), you can update this number in the file:
https://github.com/mitmedialab/sherlock-project/blob/master/models/sherlock_model.json

I cannot put a direct link to the line to update (this JSON is not formatted - single line)
Please search for 
`"name": "dense_8"`

You will see:
`"units": 78,`

It avoids the issue of shape sizes incompatible:
ValueError: Shapes (None, 1) and (None, 78) are incompatible

**Comment by madelonhulsebos** [comment]
Hi @bhart12 and @sylmorin-gbif,

Thanks for reporting these issues and collaborating on the solution. I wanted to let you know that I have added the original model code, to simplify retraining Sherlock with a different number of classes (this is inferred from the training labels automatically). You can find and use the code from the `sherlock.deploy.model.py` module, please see the renewed notebooks for details on usage. The new code also significantly speeds up feature extraction for the datasets.

I hope this helps. Let me know if you run into issues.

Best,
Madelon
