### ISSUE TITLE
`sherlock` model gives strange results

### ISSUE THREAD

**Issue by michaelmior** [mitmedialab/sherlock-project#2]
When trying predictions using the `sherlock` model, I get everything in the sample data predicted as `weight` or `symbol`. Using ` retrain_minimal_sample` gives more reasonable results. It would be helpful to have an explanation of what these two models are.

**Comment by madelonhulsebos** [comment]
Hi @michaelmior ,
Thanks for noting this issue, I'm aware of the problem and will fix this next weekend.
I will also add the original training data and model code, for replication and experimentation.
Madelon

**Comment by michaelmior** [comment]
@madelonhulsebos Thanks! If you could update this when that's fixed, that would be great :)

**Comment by nupurneti** [comment]
Hi, 

Trying to use sherlock on a new dataset and we are getting a lot of "symbol" as well 

![](https://files.slack.com/files-pri/T0NTE4YR5-F01UUSCR82K/image.png)

Was there any improvement on this? 

Also, we are trying to use `retrain_minimal_sample` as suggested in this issue, but we dont have the h5 file for it, only the json. how would we go about using `retrain_minimal_sample`?
