### ISSUE TITLE
Cannot reproduce already processed features

### ISSUE THREAD

**Issue by ycrouin** [mitmedialab/sherlock-project#26]
Hi, thanks for open-sourcing this tool :)

I tried to reproduce the `processed/X_test.parquet` dataframes from the `raw/test_values.parquet` values.
Unfortunately, I was not able to retrieve the same results using the `extract_features` function.

As we can see in the screenshot below, we don't get the same features at all, as if the dataset used to create the `processed/X_test.parquet` was not the `raw/test_values.parquet` one?

![Screenshot from 2021-05-11 21-42-51](https://user-images.githubusercontent.com/79843522/117874970-ee27da00-b2a1-11eb-877a-38324de1fb3d.png)

I attach a pdf file of my simple notebook: [demo_usage_sherlock.pdf](https://github.com/mitmedialab/sherlock-project/files/6461616/demo_usage_sherlock.pdf)

Maybe I'm not using the provided data the right way, I'm not sure.

P.S: I'm using more recent versions of python dependencies than the ones in the requirements.txt file but I don't think the issue comes from here.

**Comment by madelonhulsebos** [comment]
Hi @ycrouin,

Apologies for this late response, I hope you were able to make it work for you.
It may be that the code did not provide exact reproducibility, it has been reworked a bit.
The latest version should enable you to reproduce the performances and is much faster, with thanks to @lowecg.
Let me know if you run into issues with that, or if you have other questions!

Best,
Madelon
