### ISSUE TITLE
Where to find the global statistics features?

### ISSUE THREAD

**Issue by sitaomin1994** [mitmedialab/sherlock-project#30]
In the paper, it mentions it uses 'global statistics' features, I looked at code, only found other text features but cannot find global statistics features.

**Comment by madelonhulsebos** [comment]
Hi @sitaomin1994, 

The global statistics features can be found in [this module](https://github.com/mitmedialab/sherlock-project/blob/master/sherlock/features/bag_of_words.py), denoted as `bag_of_words.py`.

Let me know if you have questions!
