### ISSUE TITLE
275 DBpedia properties??

### ISSUE THREAD

**Issue by yuji-mizobuchi** [mitmedialab/sherlock-project#32]
Hi, Thank you for sharing your great work. I am currently interested in 275 DBpedia properties and am trying to extract them from [T2Dv2 Gold Standard data.](http://webdatacommons.org/webtables/goldstandardV2.html#toc6) However, as far as I examined, there is no extraction method that shows exactly 275 different properties. For example, if I try to extract the dbpedia URLs from all the files in the property folder, it ends up with 118 types. Please let me know how you extracted them.

**Comment by madelonhulsebos** [comment]
Hi @yuji-mizobuchi,

Apologies for the late response. I do not remember exactly how I extracted the types, but I believe just from the annotations of T2Dv2? Let me know if you haven't sorted it out yet, then I'll dig a bit deeper. For this project, we filtered out semantic types from dbpedia of which we had less than 1000 columns. All types we used are listed by a related project in table 18 of [this paper](https://adalabucsd.github.io/papers/TR_2021_SortingHat.pdf).

Hope this helps, if so please close this issue. Let me know if you have additional questions!

Best,
Madelon
