### ISSUE TITLE
improved F1 score and pre-processing performance

### ISSUE THREAD

**Issue by lowecg** [mitmedialab/sherlock-project#33]
Hello,

Firstly, thank you for this great project - I learned a lot from this :-)

I have a (substantially) re-written version of this code in a private fork for which I achieved the following results:

- F1 score > 90
- Pre-processing time for all data completes in 25 mins (on a 2013 MBP)

If you're interested, then it would be good to contribute these changes back but I don't want to dump a huge PR on you, so we might need to work out an approach that reintroduces the changes in stages.

Cheers,

Chris.

**Comment by madelonhulsebos** [comment]
Hi Chris,

Thanks a lot for noting your contribution! It seems good to integrate your improvements.
One PR seems fine to me, so that I can see the code in total. If needed, we can split it afterwards.
Let me know if you think there is a better way to integrate your contribution!

Best,
Madelon

**Comment by lowecg** [comment]
Thank you, Madelon.

I've created the following PR:

https://github.com/mitmedialab/sherlock-project/pull/34

Execution notes:

Use Python 3.7 and requirements.txt.
The Python 3.8/requirements38.txt work for feature extraction, but TensorFlow 1.x is not compatible so that's as far as it goes.

Run `demo_usage_sherlock.ipynb`, then `random-forest.ipynb` (on the first line, specify an appropriate model name for `nn_model_id`).

`random-forest.ipynb` is a slight misnomer as it also runs the NN prediction and a voting classifier.

Higher F1 score:

I achieved this by stacking the NN with an improved random forest model.

Interestingly, I recreated your quoted score for the Random Forest model with the original dependencies. As part of my experiments, I bumped the version of scikit learn and noticed a sudden jump in the random forest score to ~0.89 (which is competitive with the NN). When observing the best and worse performing scores, it seemed to do better in some areas where the NN had less confidence which made me wonder how a stacking approach might work here. Quite nicely as it turns out, and the combined model achieved a score of **0.9057**.

As for the apparent sudden jump in the random forest performance, this seems to have been down to a change in the default value for

**Comment by lowecg** [comment]
(accidentally closed)

**Comment by lowecg** [comment]
@madelonhulsebos sorry - just noticed there were a couple of files with merge conflicts. I've resolved them now.

**Comment by madelonhulsebos** [comment]
Thanks @lowecg for this contribution, and resolving the merge conflicts! I will check it out next week.

**Comment by lowecg** [comment]
Morning @madelonhulsebos 

I hope you had a good festive break and a happy new year!

Did you get a chance to look at the PR in the end?  Let me know if I can help in any way.

Chris.

**Comment by iganand** [comment]
@lowecg i am trying to run the code from your branch and i am getting error like below: looks like file is missing
FileNotFoundError: [Errno 2] No such file or directory: '../sherlock/features/par_vec_retrained_400.pkl.trainables.syn1neg.npy'

**Comment by lowecg** [comment]
Thanks for letting me know, @iganand - I'll take a look this morning.

**Comment by madelonhulsebos** [comment]
Hi @lowecg,

Thanks for your message. I definitely looked at your PR! It all looks good and useful but I wanted to review the modelling adjustments a bit further. I also need to tag the current version to keep it in line with the paper.

The actual integration will be slightly delayed as I'm busy during the next 2 weeks. Let me know if this affects your work!

Best,
Madelon

**Comment by lowecg** [comment]
Hi @iganand 

- To generate the missing file, run the notebook `train_doc2vec.ipynb`. It's a one-off task and took about 30 mins to complete on my laptop.
- Pull the latest changes from the PR: I fixed a minor fault concerning a missing folder the first run and removed a hard coding of process count

Run `demo_usage_sherlock.ipynb` again and it should run through cleanly. 

If you're running this from scratch, then you'll need to create an NN model by running `Training Only.ipynb` prior to running `random-forest.ipynb`. Each of these notebooks defines `nn_model_id`, so make sure these values are aligned.

I'll amend the docs/notebooks to make sure the above is covered in future.

Apologies for this error, and thanks again for taking the time to report it.

Chris.

**Comment by lowecg** [comment]
Thank you for taking the time to look at this @madelonhulsebos - very much appreciated!

There’s no rush for the integration on my part.

Cheers,

Chris.

**Comment by madelonhulsebos** [comment]
Hi @lowecg,

Would it work for you to have a short meeting next week to discuss the integration?
Perhaps you can send me a personal message through [twitter](https://twitter.com/MadelonHulsebos), or send me an email directly?

Best,
Madelon

**Comment by lowecg** [comment]
Hi @madelonhulsebos 

Happy to have a meeting. I resurrected my Twitter account (@lowecg) but I'm unable to DM you. Can you try to DM me instead?

Cheers,

Chris.

**Comment by madelonhulsebos** [comment]
Hi @lowecg,

I think we got through this now, so shall we close this issue?

Best,
Madelon
