### ISSUE TITLE
How do you use use our custom trained par_vec_trained_400.pkl to train our own model?

### ISSUE THREAD

**Issue by sadhiman7** [mitmedialab/sherlock-project#44]
I have created the paragraph vector as mentioned in the notebook, but how do we use it for data-preprocessing? Because prepare_feature_extraction() still downloads the pre trained paragraph vectors (3 files).

**Comment by madelonhulsebos** [comment]
Hi @sadhiman7,

Actually, the `prepare_feature_extraction()` function only downloads these files, if these are not available yet. So in your case, if you've trained the paragraph vectors yourself, it will not download the pretrained paragraph vector files.
To your other question the `.npy` file is used for initializing the trained paragraph vector model.

Hope this helps your understanding.

Best,
Madelon

**Comment by sadhiman7** [comment]
Thanks @madelonhulsebos for the response! Just one more question, is there any limit on the number of semantic types we can train ?

**Comment by kapilmayank** [comment]
@madelonhulsebos ,I have one confusion ,suppose a column has more than one semantic  will it work?

**Comment by kapilmayank** [comment]
> files w

in which function .npy files  are  actually getting initialized?

**Comment by madelonhulsebos** [comment]
You're welcome @sadhiman7; yes, you can train Sherlock with any number of classes if you initialize the `SherlockModel` from the `sherlockdeploy.model` module and use the `fit` method to train it. This will automatically infer the number of semantic types from the training labels.

Note that the capacity of the network (e.g. number of layers and/or number of nodes) may need an increase to accommodate a very large set of distinct types e.g. >200, but you can experiment with that.

**Comment by madelonhulsebos** [comment]
@kapilmayank w.r.t. the file dependencies for the pretrained paragraph vector model; they will be downloaded automatically if they are not available on the right path, and these files are loaded into the model in the `sherlock.features.paragraph_vectors` module. Did you run into any issue?

**Comment by kapilmayank** [comment]
Sure @madelonhulsebos , will do that
