### ISSUE TITLE
Number of Epochs are not changing 

### ISSUE THREAD

**Issue by kapilmayank** [mitmedialab/sherlock-project#46]
I updated the epochs to 20  and early_stopping to categroical crossentropyin model.py file but while training sherlock model from scratch it still runs for 100 epochs .Although I had imported the sherlock model file after making this change .Please help me in solving this asap

**Comment by madelonhulsebos** [comment]
Hi @kapilmayank, please see issue: mitmedialab/sherlock-project#45.
