### ISSUE TITLE
Is the data in sherlock/data/raw the full dataset?

### ISSUE THREAD

**Issue by dav-ell** [mitmedialab/sherlock-project#7]
This repository has no data in /data. However, the previous repository does, at https://github.com/madelonhulsebos/sherlock/tree/master/data/raw. Is that the full dataset used to train the model? The paper describes the dataset as the following:

> Then, we use exact matching between semantic types and column headers to extract 686,765 data columns from the VizNet corpus [14], a large-scale repository of real world datasets collected from the web, popular visualization systems, and open data portals.

Seeing as how `test_values.csv` only contains 1,000 columns, I assume this is only a very small sample of the full dataset, and that the full dataset still needs to be compiled if we are to reproduce your results. Is that right?

**Comment by madelonhulsebos** [comment]
Hi @dav-ell,

That is correct, it is too large to be stored on GitHub. You can find the original datasets here: https://drive.google.com/file/d/1-g0zbKFAXz7zKZc0Dnh74uDBpZCv4YqU/view?usp=sharing.

Kind regards,
Madelon

**Comment by dav-ell** [comment]
Great! This is very helpful to have, thank you.
