### ISSUE TITLE
How to test on new data 

### ISSUE THREAD

**Issue by gaurav326913** [mitmedialab/sherlock-project#8]
Thanks for creating such an amazing project. I am able to replicate the output using the dataset shared by you. 

However now if i want to try it on my own dataset how do i do it. What is the process to convert my raw data set into the pre-processed form . From the code and comment, i could understand that below code , takes X-test in the pre-processed form and not the raw form.
predicted_labels = predict_sherlock(X_test, nn_id='retrain_sherlock')

**Comment by tresata-kunal** [comment]
The model requires test input to be in the same format as that of the training data, that is, columns in the form of vectors of their contents.

**Comment by dav-ell** [comment]
For me, I specifically had to do:

```python
columns = # ...
matrix = []
for col in columns:
    new_record = []
    for record in dataset: # my dataset was in dictionary format
        val = record[col]
        new_record.append(val)
    matrix.append(np.array(new_record)) # Creating a numpy array before append it was very important for me
# Having `matrix` be a list, not a numpy array itself, was also important
df = pd.DataFrame({'values': matrix}) # I also had to pass it in as a dictionary for it to work right
# In `build_features.py` I had to change the build_features function to access data["values"]
```

**Comment by madelonhulsebos** [comment]
Hi @gaurav326913, thanks for raising this issue and @dav-ell and @tresata-kunal for supporting. 

This repository should be reworked to make it useful for other datasets, train the model from scratch, etc. I will have more time to look into that over the next 4 weeks. At this moment, as @dav-ell suggested, you have to put quite some effort in preparing your data in the expected format. I will clarify the steps needed and will try to make this more easy for the repository users.

**Comment by drimyus** [comment]
Hi @madelonhulsebos 

I tried to train the sherlock model with my own dataset (20 categories). I updated the number of units on sherlock_model.json from 78 to 20. Once I started the training, I saw that the loss is `nan` and the accuracy is not growing. :( 

```
32000/34405 [==========================>...] - ETA: 0s - loss: nan - categorical_accuracy: 0.0277
32256/34405 [===========================>..] - ETA: 0s - loss: nan - categorical_accuracy: 0.0277
32512/34405 [===========================>..] - ETA: 0s - loss: nan - categorical_accuracy: 0.0276
32768/34405 [===========================>..] - ETA: 0s - loss: nan - categorical_accuracy: 0.0278
33024/34405 [===========================>..] - ETA: 0s - loss: nan - categorical_accuracy: 0.0278
33280/34405 [============================>.] - ETA: 0s - loss: nan - categorical_accuracy: 0.0280
33536/34405 [============================>.] - ETA: 0s - loss: nan - categorical_accuracy: 0.0280
33792/34405 [============================>.] - ETA: 0s - loss: nan - categorical_accuracy: 0.0279
34048/34405 [============================>.] - ETA: 0s - loss: nan - categorical_accuracy: 0.0278
34304/34405 [============================>.] - ETA: 0s - loss: nan - categorical_accuracy: 0.0277
```

Can you please provide short guidance on how can I apply the sherlock algorithm on a new dataset?
Looking to hearing from you soon.
Thanks.

**Comment by ikhan94** [comment]
Hi @madelonhulsebos, I would like to use this framework on another dataset, you wrote that you are looking for an improved solution to prepare the data. So I wanted to ask you in case you have found something which is easier?

**Comment by madelonhulsebos** [comment]
Hi @ikhan94,

Yes I have rewritten the `preprocessing.py` module to this end with the functions `convert_string_lists_to_lists` and `extract_features`. Please let me know if you run into issues with this!

**Comment by ikhan94** [comment]
Hi @madelonhulsebos,

I managed to get the demo notebook to work. It was very well described and very simple. But now I have a problem for training a new data set. 

`train_sherlock(X_train, y_train, X_val, y_val, nn_id='retrained_sherlock_2');
print('Trained and saved new model.')`

I have changed y_train and y_val, so that it uses a dataset with nine examples, but I get the following error message.

ValueError: Input arrays should have the same number of samples as target arrays. Found 412059 input samples and 9 target samples.

How can I change the input samples?

**Comment by ikhan94** [comment]
Hi @madelonhulsebos,

also when I test my dataset on the trained sherlock model. I get the following error.

<img width="862" alt="Screenshot 2021-04-14 at 03 59 40" src="https://user-images.githubusercontent.com/55949998/114643382-d7f42180-9cd5-11eb-9094-83225d027b1c.png">

**Comment by madelonhulsebos** [comment]
Hi @ikhan94,

I've reworked [an example notebook](https://github.com/mitmedialab/sherlock-project/blob/master/notebooks/00-use-sherlock-out-of-the-box.ipynb) showing the process for feature extraction and using Sherlock to generate predictions. The other notebooks [in this directory](https://github.com/mitmedialab/sherlock-project/tree/master/notebooks) show how to extract features at scale and retrain the model.

Let me know if you have other questions!

**Comment by madelonhulsebos** [comment]
Hi @gaurav326913,

Please check [this notebook](https://github.com/mitmedialab/sherlock-project/blob/master/notebooks/01-data-preprocessing.ipynb) for guidance on data preprocessing and feature extraction. Note that the input data should be formatted the same as in the data in the download (read [this section of the readme](https://github.com/mitmedialab/sherlock-project/blob/master/notebooks/01-data-preprocessing.ipynb)). @lowecg has contributed faster code for feature extraction which also resolves some bugs.

Please check if this works for you and let me know if you have other questions.

Best,
Madelon
