### ISSUE TITLE
Attempting to reproduce results: feature vector normalization

### ISSUE THREAD

**Issue by dav-ell** [mitmedialab/sherlock-project#9]
I've been able to run custom data through your `build_features` function (with quite a few code changes), and I have the 1588 features that you have in your paper. However, many of these features need normalization, e.g. `n_[a]-agg-sum: 2081`. You don't describe how you normalized in your paper, you just say:

> At a high-level, we train subnetworks for each feature category except the statistical features, which consist of only 27 features. These subnetworks “compress” input features to an output of fixed dimension.

Your results are not possible to reproduce without knowledge of how you normalized your values. Any pointers?

**Comment by dav-ell** [comment]
Additionally, `train_sherlock.py` and `retrain_sherlock.ipynb` don't give any hints as to how you make it work. All the code I can find to manipulate the input is below:

```python
# `retrain_sherlock.ipynb`
train_vals = pd.read_parquet('../data/data/raw/train_values.parquet')
train_vals = train_vals['values'].apply(literal_eval)
X_train = build_features(train_vals)
X_train.fillna(train_columns_means.iloc[0], inplace=True) # fills NaN values with the mean of all other columns
train_sherlock(X_train, y_train, X_val, y_val, nn_id='retrain_sherlock')

# `train_sherlock.py`
y_train_cat, y_val_cat = _prepare_label_vectors(y_train, y_val, nn_id)
feature_cols = _prepare_feature_cols()
sherlock, callbacks = _prepare_sherlock_model(nn_id)
sherlock.fit([X_train[feature_cols['char']].values,
                X_train[feature_cols['word']].values,
                X_train[feature_cols['par']].values,
                X_train[feature_cols['rest']].values],
                y_train_cat,
                validation_data=([X_val[feature_cols['char']].values,
                                X_val[feature_cols['word']].values,
                                X_val[feature_cols['par']].values,
                                X_val[feature_cols['rest']].values],
                                y_val_cat),
                callbacks=callbacks, epochs=100, batch_size=256)
```

...and that's it. Nowhere do I see values being normalized. Are they not, perhaps...?

**Comment by madelonhulsebos** [comment]
Thanks for your effort on figuring this out @dav-ell. As we discussed offline, the feature vectors are indeed normalized.

This normalization is applied within the NN model. The first layer in each 'subnetwork' is a BatchNormalization layer. The first layer of the main network, after all subnetworks are merged, is also a BatchNormalization layer. 

The code can be found in the 'model_code' branch, but I agree that this repository needs work to clarify this so thanks for flagging this issue!

**Comment by dav-ell** [comment]
Thanks @madelonhulsebos. I didn't even know about the other branch, so that's helpful to hear.

Appreciate your response. You answered my question, so I'll close this issue.
